spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/devopsbingo
    username: root
    password:
management:
  security:
    enabled: false

---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://devopsbingo-mysql:3306/devopsbingo
    tomcat:
      initial-size: 0
